make ForecastScope again, remove ForecastScopeID
Open-Orange-Button/Orange-Button-Taxonomy pull request #105
Opened 2022-09-18 15:54 UTC by cwhanse

Closes #98

2022-09-18 19:02 UTC, jrippingale approved these changes
I didn't realize we had an external id value also.  Thank you for aligning this!

2022-09-23 22:10 UTC, jrippingale requested changes
The description references Forecase (rather than forecast in the whatnew file

2022-09-26 21:37 UTC, cwhanse commented on docs/whatsnew/2207.1.0.rst
> +* Remake ForecastScope and attach to Forecase (:pull:`105`)
```suggestion
* Remake ForecastScope and attach to Forecast (:pull:`105`)
```

2022-09-30 21:34 UTC, jrippingale approved these changes
Looks correct to me!  Thank you!

2022-09-30 21:34 UTC, merged