Adds ProdID to Product superclass
Open-Orange-Button/Orange-Button-Taxonomy pull request #174
Opened 2023-01-06 22:37 UTC by kevinkirkl3y

2023-01-06 23:22 UTC, jrippingale approved these changes
Looks perfect to me!

2023-01-07 17:38 UTC, reepoi requested changes

2023-01-07 17:38 UTC, reepoi commented on Master-OB-OpenAPI.json
> +            "description": "Unique identifier for the Product. ",
```suggestion
            "description": "Unique identifier for the Product.",
```
Just some trailing whitespace to remove.

2023-01-10 18:30 UTC, reepoi approved these changes

2023-01-10 19:01 UTC, cwhanse approved these changes

2023-01-13 23:09 UTC, merged