Creates JobStatus and SiteStatus elements.
Open-Orange-Button/Orange-Button-Taxonomy pull request #221
Opened 2023-04-05 16:14 UTC by kevinkirkl3y

Draft of elements to represents status of Site and Job. Closes #202, #200 .

2023-04-07 15:53 UTC, cwhanse commented
I'm OK with the element names, a little puzzled by the "\" characters in the sample values. Are we thinking to create enumerations for these?

2023-04-07 16:54 UTC, kevinkirkl3y commented
@cwhanse That was my bad. I fixed the sample values. I do think we may want to generate an enumerated list for these values but I wasn't sure if we wanted to create a specific Item type in order to that.

2023-04-07 21:36 UTC, jrippingale reviewed
Let's remove Site Status and add JobStatus with enumerated JobStatusItemType

2023-04-14 20:01 UTC, cwhanse approved these changes

2023-04-14 20:01 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "label": "Sales-Postponed\t",
delete tab character
```suggestion
          "label": "Sales-Postponed",
```

2023-04-14 21:32 UTC, kevinkirkl3y commented
Rename Sales-Postponed to Sales-Lost

2023-04-14 21:34 UTC, jrippingale requested changes
Let's remove Sales-Postponed and Sales-Closed
rename Lost to Sales-Lost

2023-04-14 23:19 UTC, jrippingale approved these changes

2023-04-17 15:09 UTC, cwhanse commented
@kevinkirkl3y ready to merge after dealing with the inevitable conflicts

2023-04-21 21:34 UTC, merged

2023-04-21 21:35 UTC, jrippingale approved these changes