Adds ChecksumType element and relative Item Type w Enums, updates wha…
Open-Orange-Button/Orange-Button-Taxonomy pull request #291
Opened 2024-02-13 21:01 UTC by kevinkirkl3y

…tsnew

2024-02-13 23:42 UTC, cwhanse approved these changes

2024-02-19 16:08 UTC, jrippingale requested changes
Kevin, please try to add descriptions of the source of the different checksum types.  Thank you!

2024-02-20 19:10 UTC, kevinkirkl3y commented
> Kevin, please try to add descriptions of the source of the different checksum types. Thank you!

@jrippingale @cwhanse  I found the references here: https://csrc.nist.gov/glossary?sortBy-lg=relevance&ipp-lg=100

2024-02-20 19:20 UTC, jrippingale approved these changes
Lovely descriptions!

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "Cyclical Redundancy Check - NIST SP 800-72"
This defines the term Cyclical Redundancy Check but there are literally dozens of such checks. Knowing it's a CRC is probably not enough information to decode a checksum.

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "Message Digest 5 - NIST SP 800-45 Version 2, NIST SP 800-101 Rev. 1"
I think we should reference RFC 1321, April 1992.  Those NIST documents are guidelines on email and device security.

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "Secure Hash Algorithm 1 - NIST SP 800-22 Rev. 1a"
Reference "FIPS 180-2"

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "Secure Hash Algorithm 2 - CNSSI 4009-2015"
Reference "FIPS 180-2"

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "Secure Hash Algorithm 3 - NIST SP 800-185"
Reference "FIPS 180-2"

2024-02-23 20:13 UTC, cwhanse commented on Master-OB-OpenAPI.json
> +          "description": "The family of all sponge functions with a KECCAK-f permutation as the underlying function and multi-rate padding as the padding rule. KECCAK was originally specified in [2],
Reference "FIPS 202" I wouldn't try to say more.

2024-02-27 20:09 UTC, cwhanse approved these changes

2024-02-29 16:52 UTC, merged