Creates InsurancePolicy object, required elements/types.
Open-Orange-Button/Orange-Button-Taxonomy pull request #89
Opened 2022-08-26 22:09 UTC by kevinkirkl3y

2022-08-30 17:27 UTC, jrippingale requested changes
The AHJ Level Code is still in this pull request.  Is that expected?

2022-09-02 18:07 UTC, cwhanse approved these changes

2022-09-12 18:42 UTC, cwhanse commented
@kevinkirkl3y this one is next when you are able to resolve the conflicts.

2022-09-16 22:34 UTC, closed without merging

2022-09-16 22:43 UTC, cwhanse commented
Superceded by #103